apiVersion: batch/v1
kind: CronJob
metadata:
  name: football-prediction-cronjob
spec:
  schedule: "0 0 * * *"
  timeZone: "Asia/Seoul"   # K8s CronJob 기본값은 UTC라, 이걸 안 주면 자정(KST)이 아니라 UTC 자정(=KST 오전 9시)에 돈다
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bq-sa   # <--- (추가) 새 신분증을 들고 실행하라는 뜻!
          containers:
          - name: pipeline-container
            image: asia-northeast3-docker.pkg.dev/football-prediction-pipeline/football-repo/predict-pipeline:v17
            imagePullPolicy: Always
            command: ["python", "-u", "src/loader.py"]
            env:
            - name: PYTHONPATH
              value: "/app/src"
            - name: FOOTBALL_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: football-api-key
                  key: FOOTBALL_DATA_API_KEY 
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-webhook
                  key: DISCORD_WEBHOOK_URL
          restartPolicy: OnFailure
